services:

  fastapi_app:
    container_name: fastapi
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - .:/app  # Bind mount current directory to /app in the container
      # - ./db:/app/db # bind database users
      # - ./models/market.db:/app/models/market.db # bind databse market price
    networks:
      - traefik_network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.fastapi.rule=Host(`fastapi.imannasr.com`)"
      - "traefik.http.routers.fastapi.entrypoints=web,websecure"
      - "traefik.http.routers.fastapi.tls.certresolver=letsencrypt"
      - "traefik.http.services.fastapi.loadbalancer.server.port=8000"
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  traefik_network:
    external: true